### ISSUE TITLE
Why are "double quoted" values treated as an SQLIdentifier instead of SQLValue

### ISSUE THREAD

**Issue by dvaldivia** [andygrove/sqlparser-rs#127]
Hi, For queries such as `SELECT * FROM table WHERE field="lol"` the value side of the expression `field="lol"` is being treated as a SQLIdentifier instead of a `SQLValue` is this intended behavior?  Why not treat it the same as a `sqlast::Value::SingleQuotedString`?

**Comment by nickolay** [comment]
Hey! Yes, that's intended: [the standard and most DBs (except in backwards-compatible mode) treat it that way](https://en.wikibooks.org/wiki/SQL_Dialects_Reference/Data_structure_definition/Delimited_identifiers#cite_note-MySQL_ANSIMode-2). You [can override this in a custom dialect though](https://github.com/andygrove/sqlparser-rs/blob/ed76cd68f8da83c0c8429d89335057e58fc6ca17/src/dialect/mod.rs#L27).

**Comment by nickolay** [comment]
> You can override this in a custom dialect though.

Er, you can prevent `".."` being treated as an identifier via a dialect, but to make it produce a string, you'll have to hack [the tokenizer](https://github.com/andygrove/sqlparser-rs/blob/ed76cd68f8da83c0c8429d89335057e58fc6ca17/src/tokenizer.rs#L314)... Do you need this for some reason? I thought using `".."` for strings in SQL was pretty rare nowadays.
