### ISSUE TITLE
Parser mishandles quoted column names

### ISSUE THREAD

**Issue by apparebit** [andygrove/sqlparser-rs#140]
The tokenizer nicely handles quoted column names, independent of dialect, e.g., `[column name]`, `"column name"`, and `` `column name` `` are all correctly recognized and the unquoted identifier `column name` is stored in the `value` slot of the corresponding `Word`. But then the parser's [`as_ident()`](https://github.com/andygrove/sqlparser-rs/blob/c7021ed145c59f9684bac6a14d63ddb66ec4aa17/src/parser.rs#L2069) restores the quotes by calling `to_string()` instead of just returning the value of `self.value`. I can't speak to all 7 lines that invoke this method but this seems the wrong implementation at least when parsing [column names](https://github.com/andygrove/sqlparser-rs/blob/c7021ed145c59f9684bac6a14d63ddb66ec4aa17/src/parser.rs#L979) as well as [parsing identifiers](https://github.com/andygrove/sqlparser-rs/blob/c7021ed145c59f9684bac6a14d63ddb66ec4aa17/src/parser.rs#L1369). If there are no objections, I'm gonna submit a pull request to fix this.

**Comment by nickolay** [comment]
That's because `Ident` is currently simply a `String`, which ought to serialize back into valid SQL; ideally close to the original.

If `Ident` stored an unquoted string, it would also need to store the `quote_style` (like `Word` does) or to have some logic that decides when to quote idents during serialization... Alternatively there could be a helper that allows the consumer to get the "value" of the `Ident`.

**Comment by apparebit** [comment]
That's really too bad because it has the parser undo work already performed by the tokenizer. Wouldn't it make more sense to check during pretty-printing whether an identifier needs quoting and then apply the correct quotes for the given SQL dialect? Otherwise, any planner would have to check identifiers for quote characters and strip them off, which means duplicating functionality and doing so in the wrong place.

**Comment by nickolay** [comment]
> Wouldn't it make more sense to check during pretty-printing whether an identifier needs quoting and then apply the correct quotes for the given SQL dialect?

Not sure: for example, according to https://lerner.co.il/2013/11/30/quoting-postgresql/ `CREATE TABLE "People"` and `CREATE TABLE People` are not equivalent in postgres. And the "correct" quotes usually depend not only on the dialect, but on the options in effect for the session... it's a mess as usual.

Storing the `quote_style` in the AST seems easier to implement and more likely to be correct, doesn't it?

> Otherwise, any planner would have to check identifiers for quote characters and strip them off, which means duplicating functionality and doing so in the wrong place.

I agree! (Before I implemented it this way the quoted identifiers were not parsed properly, so even this limited implementation was an improvement.)

**Comment by apparebit** [comment]
You mean replacing `type Ident` with a `struct Ident`, which mirrors `Word`'s `value` and `quote_style` fields, right? I like that idea a lot because it preserves already derived information yet allows for dialect-specific handling. If so, I'll try to make that change:

  * Change the definition of `Ident` to become a struct;
  * Turn `Word::as_ident()` into `to_ident()`, which copies the `value` and `quote_style`;
  * Implement `Display` for `Ident` just as it is currently implemented for `Word`.

Does that sound good?

**Comment by nickolay** [comment]
Yep, I think that should work. Thanks!
