### ISSUE TITLE
Support case sensitive parsing

### ISSUE THREAD

**Issue by mitar** [andygrove/sqlparser-rs#144]
So by standard SQL queries are not case sensitive. But for me, this is problematic because I like to encode metadata information into database structures (like table names, column names, etc.) so that database introspection can work well. But then this means I have to quote all names all the time in all SQL queries.

So I would love if this package could support case sensitive parsing (and unparsing, #18). This could allow one to read (and rewrite) queries without changing the case.

I am mentioning this because as this package becomes more SQL standardized, it would be useful to keep some extensions available (like case sensitivity).

**Comment by benesch** [comment]
This package already preserves the case of identifiers. Do you have a specific example of something that doesn’t work for you?

**Comment by mitar** [comment]
Yes, but with other issues like #17 I would like just to make sure that this is a conscious decision to support and not something which disappears.

**Comment by benesch** [comment]
It absolutely is intentional! Normalization is intentionally left to the
client. If we ever fold in normalization support, we’ll retain a dialect
that performs no normalization (the generic dialect).
