### ISSUE TITLE
Example to how to extend the current implementation with custom keywords and inner structs

### ISSUE THREAD

**Issue by vertexclique** [andygrove/sqlparser-rs#146]
I want to use this crate as a dependency to implement my own keywords and operations. It would be really nice to see a concrete example.

**Comment by nickolay** [comment]
That's not possible. Your options are to submit a PR if it's a missing feature defined in the standard or supported by a popular DB or make your own fork... As I understand, #7 was supposed to track improvements in this area, but it was stalled.

P.S. I'm sorry no-one answered you earlier!
