### ISSUE TITLE
SELECT TOP N syntax (i/o LIMIT) for MSSQL

### ISSUE THREAD

**Issue by alexkyllo** [andygrove/sqlparser-rs#149]
This is minor but seemed like potentially a good first issue, and the README mentioned you were interested in PRs to add support for RDBMS like MS SQL Server:

SQL Server syntax for limiting the result set is `SELECT TOP N ...` or `SELECT TOP(N) ...` optionally followed by `PERCENT` and/or `WITH TIES` -- see [Microsoft Docs link](https://docs.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql?view=sql-server-ver15). I don't see `TOP` in the keyword list and was able to create a failing test for parsing this. Thinking of submitting a PR to add support for this syntax.

**Comment by benesch** [comment]
Please do! That sounds like a great first issue to tackle.
