### ISSUE TITLE
Fail to parse - "select * from (table_name)"

### ISSUE THREAD

**Issue by eyalleshem** [andygrove/sqlparser-rs#154]
I think it's fail here - https://github.com/andygrove/sqlparser-rs/blob/master/src/parser.rs#L1797 
because the code assume that inside the Parenthesis should be TableFactor::Derived  or TableFactor::NestedJoin,  but it's not take in account it's could be TableFactor::Table

**Comment by nickolay** [comment]
`from (table_name)` is not actually valid SQL. Note that `<table primary>` in the [ANSI SQL grammar](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_7_5_from_clause) does not allow parentheses around `<table or query name>`. A quick test shows that at least MS SQL Server follows the spec here. What database are you working with?

**Comment by eyalleshem** [comment]
Thanks for the quick response :)  

I testest against snowflake ..
Is that something that could be solve by building a dialect ?

**Comment by nickolay** [comment]
Theoretically, yes. Practically in the current implementation the selected dialect only affects the tokenizer, and the parser unconditionally tries to parse some non-standard constructs.

**Comment by eyalleshem** [comment]
So a code that support such syntax could be accepted?

**Comment by nickolay** [comment]
I guess so, if it's going to be a simple change, that doesn't introduce problems parsing the standard syntax (this specific bit of the parser is quite complex as it is). @benesch what do you think?

**Comment by eyalleshem** [comment]
well - i tried :)

**Comment by nickolay** [comment]
PR #155 is now merged, closing this. Thanks!
