### ISSUE TITLE
CAST expressions

### ISSUE THREAD

**Issue by andygrove** [andygrove/sqlparser-rs#16]
https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html#_6_13_cast_specification

**Comment by nickolay** [comment]
We [support](https://github.com/andygrove/sqlparser-rs/blob/64b1ea7a254388e80dbd8ac196a6533c9a5a5d3b/src/sqlparser.rs#L285) parsing `CAST` itself, and have done so since before this issue was filed. Should it be closed?

**Comment by andygrove** [comment]
Yes, I think so. Thanks.
