### ISSUE TITLE
ANSI SQL String concatenation operator `||`

### ISSUE THREAD

**Issue by christoshadjiaslanis** [andygrove/sqlparser-rs#160]
Hi.

Great crate thank you very much for your work.

I think there isn't support for ANSI SQL String concatenation:

`SELECT "a" || "b" FROM ...`

Is there plan to support this soon?

I think most SQL dialects support the `CONCAT` function, but I don't think it's ANSI SQL.

**Comment by nickolay** [comment]
Hi! You're right that `||` is the standard way to concatenate strings (per [6.31 &lt;string value expression>](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_6_31_string_value_expression)), unlike `CONCAT`. I don't know of anyone working to implement it, so if you were thinking to make a pull request, it would be most welcome!

**Comment by christoshadjiaslanis** [comment]
Maybe label it as 'help wanted'.

If I find some time I'll give it a shot.

**Comment by nickolay** [comment]
Fixed in #178.
