### ISSUE TITLE
Fix broken code coverage

### ISSUE THREAD

**Issue by nickolay** [andygrove/sqlparser-rs#164]
As noted in https://github.com/andygrove/sqlparser-rs/pull/159 , `cargo coveralls` fails in CI with an error due to a change in Cargo.lock format. This is supposed to be fixed in https://github.com/roblabla/cargo-travis/issues/66 , but simply upgrading to that version didn't work for me resulting in linking errors. I did not investigate further.

**Comment by Dandandan** [comment]
What about using https://github.com/xd009642/tarpaulin ?

**Comment by nickolay** [comment]
I don't know the difference. Whatever works and produces usable coverage info will do, I suppose. The issue is someone willing to put in the work!

**Comment by maxcountryman** [comment]
I'm curious about GitHub Actions as well: I've recently switched over some repos from Travis to Actions and so far it seems to be a nice change. In particular, the configuration is a little more straightforward and there's a nice ecosystem of Actions that are easy to use.

**Comment by maxcountryman** [comment]
I didn't realize there was already a GitHub Actions workflow! 🙂 I put together a quick refactor in case that's a direction you want to go in.
