### ISSUE TITLE
column names that conflict with DATE/TIME keywords must be quoted

### ISSUE THREAD

**Issue by jrmuizel** [andygrove/sqlparser-rs#168]
Postgresql has no problem parsing the query `select date from default` but sqlparser-rs does:
```
2020-05-24 13:56:55,466 DEBUG [sqlparser::parser] Parsing sql 'select date from default
'...
2020-05-24 13:56:55,467 DEBUG [sqlparser::parser] parsing expr
Error during parsing: ParserError("Expected literal string, found: from")
```

**Comment by nickolay** [comment]
Thanks for the report!

Using `DATE` as a column name is not universally supported (MSSQL, for example, also bails on it).

But yes, Postges supports DATE both as a part of the `DATE 'yyyymmdd'` literal and as a column name (if not followed by a string literal). It [generalizes it](https://www.postgresql.org/docs/12/datatype-datetime.html#DATATYPE-DATETIME-INPUT)  to [`type name [ (optional_precision_and_scale) ] 'literal string'` syntax](https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS-GENERIC), requiring look-ahead to properly handle this.

Someone would have to port https://github.com/MaterializeInc/materialize/pull/3146 to fix this.

**Comment by maxcountryman** [comment]
I'll also add that I ran into this issue with Redshift (a derivative of Postgres originally).
