### ISSUE TITLE
Add `serde` support to AST structs and enums

### ISSUE THREAD

**Issue by panarch** [andygrove/sqlparser-rs#183]
Hello, I found that `serde` is not applied in this project, so there's no easy way to serialize/deserialize AST nodes.
`serde` is often quite useful for some cases; considering to parse query and store the result in somewhere, or parsing remotely and send to database over network... etc.

It looks good to add `serde` as optional like `bigdecimal`.
then something similar with this below will be added.
```toml
# Cargo.toml
serde = { version = "1.0", features = ["derive"], optional = true }
```

And for every `ast/` codes,
```rust
#[cfg(feature = "serde")]
use serde::{Serialize, Deserialize};

/// Unary operators
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum UnaryOperator {
    Plus,
    Minus,
    Not,
}
```

How do you think of this? If it is ok, then I'd like to work on this issue.

**Comment by nickolay** [comment]
I agree. I actually add this by hand to my local copy every now and then using two global replacements:

* Search for `#[derive(Debug, Clone, PartialEq, Eq, Hash)]` to append Serialize/Deserialize
* Search for `use std::fmt;` and prepend `use serde::{Serialize, Deserialize};`

...but if I'm not alone, it's probably a good idea to include it in the crate, via an optional feature, as you suggest.

**Comment by panarch** [comment]
@nickolay Thanks, it's so good to see that I'm not the only one who needs `serde`.
I also worried about that someone may think `serde` is totally not necessary feature to have.
So... that was why I suggested to add as an optional feature, `cfg` is really cool.

I'm currently migrating a parser of my existing sql db project from `nom-sql` to `sqlparser-rs`, this one.
In `nom-sql`, it supports `serde` so I used a lot and my project is quite depending on `serde`.
I'm using `serde` to store table schema, by using data types from provided by parser.

And... because I should use `serde`, so I actually already finished applying it on my local copy, like you.
https://github.com/panarch/sqlparser-rs/commit/9335c346d923d1439243e59e95eabde51e539fb4
Here you can see, I forked and it is in my `serde` branch.

Hope to get positive feedback from others.

**Comment by Dandandan** [comment]
Serde support could be quite useful. I agree as an optional feature would be the best, to avoid longer compile times.

**Comment by panarch** [comment]
Due to https://github.com/andygrove/sqlparser-rs/pull/189
https://github.com/nickolay/sqlparser-rs/commit/5ba4a554159016db20bf2bbfb40f52066d753da4 already added `serde` so I'll just leave my local branch without requesting PR. 👌

**Comment by nickolay** [comment]
That's just an instance of _adding this by hand to my local copy_, not intended to be merged (it's not optional, for one). Please feel free to PR your branch.

**Comment by panarch** [comment]
Ok, then I'll make PR, thanks :)
