### ISSUE TITLE
Add some benchmarks

### ISSUE THREAD

**Issue by Dandandan** [andygrove/sqlparser-rs#188]
It would be nice to have some numbers on the performance of this parser. There are probably a few hotspots in the code, but without any numbers it is hard to find those.

We can maybe start with a few simple criterion benchmarks, like

created in forma/formation:
https://github.com/maxcountryman/forma/blob/master/formation/benches/formation_bench.rs

**Comment by nickolay** [comment]
I'm in favor of adding something like this as a template to help with profiling, if we take care not to regress the build time for those not running the benchmarks.

But I don't see a problem with performance at this stage, and I don't think it should be a goal of this library to achieve the highest possible number of parses/second. For example, I'm going to trade being able to track position information (#161) for some performance.

**Comment by Dandandan** [comment]
Yes, agree. However we probably can have the same functionality, while being faster, or track regressions a bit better.

**Comment by nickolay** [comment]
Sure. Do you want to whip up a PR or should I mark this helpwanted?

**Comment by Dandandan** [comment]
I probably make a PR soon!

**Comment by Dandandan** [comment]
Fixed!

https://github.com/andygrove/sqlparser-rs/pull/190
