### ISSUE TITLE
New Crates release?

### ISSUE THREAD

**Issue by maxcountryman** [andygrove/sqlparser-rs#204]
I'm wondering if it's possible to author a new Crates release containing the recent changes? It seems that without a published crate, I'm [unable to bring these changes into my own crates](https://github.com/rust-lang/cargo/pull/7237/#issuecomment-532283875).

**Comment by nickolay** [comment]
You'll have to get hold of @andygrove for that, as he's the only one who can do a release.

**Comment by Dandandan** [comment]
Would it an idea to keep the crates.io secrets in GitHub so we can setup an automated way of releasing via a workflow (with git tags for example).

**Comment by Dandandan** [comment]
Like this: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow

And yes, I would also would love a new release for the recent `create table as` addition :).

**Comment by andygrove** [comment]
This sounds good. I'm also open to giving others permissions to publish.

**Comment by andygrove** [comment]
I can take care of a release this evening to at least unblock people for now.

**Comment by andygrove** [comment]
0.5.1 is published. In hindsight I should probably have released as 0.6.0. Hopefully there aren't any major breaking changes.

**Comment by Dandandan** [comment]
Super, thanks!

**Comment by nickolay** [comment]
@andygrove  Thanks! I've updated the changelog to note that: https://github.com/andygrove/sqlparser-rs/commit/0c82be5c3b34e3409607e34f14e0f45dae9dc4dd

**Comment by maxcountryman** [comment]
Thanks, Andy!

**Comment by Dandandan** [comment]
Would it maybe be an idea to either give someone else permission to publish? I think @nickolay is the most active in here . We could also setup this for publishing a crate:

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow

This could work the same way like @maxcountryman has implemented for forma:

https://github.com/maxcountryman/forma/blob/master/.github/workflows/main.yml#L88

**Comment by andygrove** [comment]
I would be happy to give permissions to others. I think I would just need
their crates.io username.

**Comment by nickolay** [comment]
Thanks, I've registered https://crates.io/users/nickolay , but if anyone else is willing to take care of the release process, I'd be happy to stand back.

In particular, if @Dandandan or @maxcountryman volunteered (wink), I would be in favor of giving them the necessary permissions. They have been active on the project recently, and it would be an honor to have them on the team officially!

**Comment by Dandandan** [comment]
I would like to help with this!

If you also add me to the GitHub repo I can also implement the tag-based release process like I linked to.

My github / crates handle is Dandandan.

**Comment by andygrove** [comment]
ok @Dandandan aND @nickolay you should both have invites got crates.io and @Dandandan also has an invite to collaborate on this repo.

I just moved the repo under the ballista-compute org as well.

**Comment by maxcountryman** [comment]
It sounds like there's enough people to take care of the processes, but if it's helpful I'm also happy to volunteer. 🙂

**Comment by andygrove** [comment]
@maxcountryman Invites sent!

**Comment by maxcountryman** [comment]
Thanks, Andy!
