### ISSUE TITLE
Semver for 0.5.1

### ISSUE THREAD

**Issue by hwchen** [andygrove/sqlparser-rs#210]
Hello,

Can you clarify why 0.5.1 was not 0.6.0, when there was a major breaking change? The changelog makes some mention, but doesn't really explain the reasoning.

It broke my CI; not the end of the world, but it was a bit confusing.

(And also, thanks for the work, it's a great library. This wouldn't be an issue for me if I wasn't depending on it for something important).

**Comment by Dandandan** [comment]
Hi @hwchen . See this issue for the exact reason

https://github.com/andygrove/sqlparser-rs/issues/204

definitely something to avoid in the future!

**Comment by hwchen** [comment]
Ah, I see. Thanks for pointing me to the issue!
