### ISSUE TITLE
Unary minus 

### ISSUE THREAD

**Issue by cswinter** [andygrove/sqlparser-rs#29]
Expressions with unary minus fail to parse.
Examples:
```
SELECT -2 + a FROM test;
SELECT (-2) + a FROM test;
SELECT a + -b FROM test;
```

Similar queries seem to parse in MySQL: http://sqlfiddle.com/#!9/a6c585/79181

**Comment by nickolay** [comment]
This was implemented in 54c9ca86193d25fa29a2cd774a274bc9755dfabc
