### ISSUE TITLE
Support EXISTS(subquery)

### ISSUE THREAD

**Issue by andygrove** [andygrove/sqlparser-rs#5]

**Comment by nickolay** [comment]
Subqueries are now supported in CTEs (`WITH`), derived tables (`FROM (SELECT ...)`), in scalar context, and with `IN`.

`EXISTS` is the only common construct I can think of that we don't implement.

**Comment by nickolay** [comment]
Updated the summary per previous comment. This should be easy to add to `parse_prefix`.

https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html#_8_10_exists_predicate
