### ISSUE TITLE
SELECT query with LIMIT clause but no WHERE clause fails to parse.

### ISSUE THREAD

**Issue by ivanceras** [andygrove/sqlparser-rs#67]
This passes
```sql
SELECT id, fname, lname FROM customer WHERE 1 = 1 LIMIT 5
```
But this one fails:
```sql
SELECT id, fname, lname FROM customer LIMIT 5
```

**Comment by ivanceras** [comment]
It looks like limit keyword is interpreted as table alias since this invalid query parses.
```sql
SELECT id, fname, lname FROM customer LIMIT LIMIT 5
```
However, adding LIMIT to the [reserved for table alias](https://github.com/andygrove/sqlparser-rs/blob/master/src/dialect/keywords.rs#L392) did NOT fix the issue.

**Comment by ivanceras** [comment]
Turns out I'm using and testing an older version of the code.
Well, so much for rubberducking.  :)

**Comment by dvaldivia** [comment]
Will this fix be released soon?

**Comment by benesch** [comment]
Hi @dvaldivia, I'm afraid I don't have a concrete answer for you, but there is a general sense that it's time for a new release soon ([some details](https://github.com/andygrove/sqlparser-rs/pull/105#issuecomment-500672700)). I'll launch a new issue so we have somewhere to centralize this discussion.

**Comment by benesch** [comment]
Ok, I've filed https://github.com/andygrove/sqlparser-rs/issues/117 to continue the discussion.
